In [139]:
import numpy as np

In [140]:
oned_arr = np.array([1,2,3,4,5])
twod_arr = np.array([[1,2,3,4],[5,6,7,8]])
threed_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

oned_arr, twod_arr, threed_arr

(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

In [11]:
shapee = oned_arr.shape
dimension = oned_arr.ndim
data_type = oned_arr.dtype
sizee = oned_arr.size
typee = type(oned_arr)

shapee, dimension, data_type, sizee, typee

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [12]:
shapee = twod_arr.shape
dimension = twod_arr.ndim
data_type = twod_arr.dtype
sizee = twod_arr.size
typee = type(twod_arr)

shapee, dimension, data_type, sizee, typee

((2, 4), 2, dtype('int32'), 8, numpy.ndarray)

In [13]:
shapee = threed_arr.shape
dimension = threed_arr.ndim
data_type = threed_arr.dtype
sizee = threed_arr.size
typee = type(threed_arr)

shapee, dimension, data_type, sizee, typee

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [141]:
import pandas as pd

df = pd.DataFrame(twod_arr)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [17]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
random_arr = np.random.uniform(0,10,(7,2))
random_arr

array([[1.01824501, 1.26352506],
       [2.72472965, 6.94007194],
       [2.37535382, 2.48462322],
       [4.566633  , 7.39593178],
       [9.29638164, 0.9014928 ],
       [2.59169193, 1.31253303],
       [2.1593084 , 7.7541963 ]])

In [29]:
random_array1 = np.random.random((3,5))
random_array1

array([[0.53211101, 0.05090784, 0.32743193, 0.54983281, 0.49204783],
       [0.48576821, 0.04272874, 0.50205777, 0.88656583, 0.97847998],
       [0.37133928, 0.99785403, 0.64805594, 0.14537257, 0.77718673]])

In [31]:
random_arr2 = np.random.randint(10,size = (3,3))
random_arr2

array([[3, 3, 2],
       [1, 7, 5],
       [1, 9, 9]])

In [33]:
random_arr3 = np.random.rand(3,3)
random_arr3

array([[0.75203314, 0.26376809, 0.91118615],
       [0.93858239, 0.74749773, 0.36275889],
       [0.76206145, 0.60547652, 0.58456755]])

In [39]:
np.random.seed(99)
random_arr1 = np.random.randint(10,size = (4,6))
random_arr1

array([[1, 3, 9, 8, 9, 8],
       [2, 4, 5, 4, 1, 7],
       [3, 7, 1, 1, 0, 6],
       [4, 7, 2, 0, 8, 8]])

In [45]:
random_array = np.random.randint(10, size = (3,7))

random_array

unique_numbers = np.unique(random_array)

random_array, unique_numbers

(array([[5, 5, 1, 5, 0, 2, 7],
        [0, 6, 7, 2, 8, 6, 4],
        [2, 5, 0, 1, 7, 0, 5]]),
 array([0, 1, 2, 4, 5, 6, 7, 8]))

In [46]:
random_array[0]

array([5, 5, 1, 5, 0, 2, 7])

In [47]:
random_array[:2]

array([[5, 5, 1, 5, 0, 2, 7],
       [0, 6, 7, 2, 8, 6, 4]])

In [48]:
random_array[:2,:2]

array([[5, 5],
       [0, 6]])

In [50]:
ones_array = np.ones((3,5))
random_array = np.random.randint(10,size = (3,5))

ones_array, random_array

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[3, 5, 9, 8, 3],
        [1, 5, 0, 0, 7],
        [7, 0, 7, 7, 4]]))

In [51]:
addition = ones_array + random_array
addition

array([[ 4.,  6., 10.,  9.,  4.],
       [ 2.,  6.,  1.,  1.,  8.],
       [ 8.,  1.,  8.,  8.,  5.]])

In [52]:
another_ones = np.ones((5,3))
another_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
addition + another_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [54]:
addition + another_ones.T

array([[ 5.,  7., 11., 10.,  5.],
       [ 3.,  7.,  2.,  2.,  9.],
       [ 9.,  2.,  9.,  9.,  6.]])

In [56]:
ones_array = np.ones((3,5))

In [59]:
substraction = addition - ones_array
substraction

array([[3., 5., 9., 8., 3.],
       [1., 5., 0., 0., 7.],
       [7., 0., 7., 7., 4.]])

In [61]:
multiplication = addition - ones_array
multiplication

array([[3., 5., 9., 8., 3.],
       [1., 5., 0., 0., 7.],
       [7., 0., 7., 7., 4.]])

In [62]:
square = addition ** 2
square

array([[ 16.,  36., 100.,  81.,  16.],
       [  4.,  36.,   1.,   1.,  64.],
       [ 64.,   1.,  64.,  64.,  25.]])

In [63]:
square_2 = np.square(addition)
square_2

array([[ 16.,  36., 100.,  81.,  16.],
       [  4.,  36.,   1.,   1.,  64.],
       [ 64.,   1.,  64.,  64.,  25.]])

In [65]:
random_arr = np.random.randint(10, size = (3,3))
random_arr

array([[8, 7, 7],
       [5, 2, 2],
       [3, 0, 6]])

In [66]:
random_arr.mean()

4.444444444444445

In [71]:
random_arr.min(axis = 1), random_arr.min(axis = 0)

(array([7, 2, 0]), array([3, 0, 2]))

In [75]:
random_arr.max(axis = 1), random_arr.max(axis = 0)

(array([8, 5, 6]), array([8, 7, 7]))

In [78]:
random_arr.max(),random_arr.min()

(8, 0)

In [79]:
np.std(random_arr)

2.629368792488718

In [80]:
np.var(random_arr)

6.91358024691358

In [86]:
random_arr = np.random.randint(10,size = (5,3))
reshaped_array = random_arr.reshape(3,5,1)
reshaped_array

array([[[5],
        [5],
        [6],
        [7],
        [9]],

       [[6],
        [1],
        [8],
        [8],
        [4]],

       [[2],
        [2],
        [6],
        [1],
        [0]]])

In [87]:
reshaped_array.T

array([[[5, 6, 2],
        [5, 1, 2],
        [6, 8, 6],
        [7, 8, 1],
        [9, 4, 0]]])

In [90]:
random_arr1 = np.random.randint(10,size = (3,3))
random_arr2 = np.random.randint(10,size = (3,2))
random_arr1, random_arr2

(array([[6, 0, 5],
        [1, 3, 5],
        [9, 4, 1]]),
 array([[7, 7],
        [1, 4],
        [8, 8]]))

In [91]:
random_arr1.dot(random_arr2)

array([[82, 82],
       [50, 59],
       [75, 87]])

In [92]:
np.dot(random_arr1,random_arr2)

array([[82, 82],
       [50, 59],
       [75, 87]])

In [94]:
random_arr1 = np.random.randint(10,size = (4,3))
random_arr2 = np.random.randint(10, size = (4,3))
random_arr1, random_arr2

(array([[5, 6, 2],
        [7, 5, 6],
        [5, 8, 3],
        [2, 7, 1]]),
 array([[0, 6, 3],
        [3, 6, 1],
        [0, 9, 2],
        [4, 4, 3]]))

In [95]:
np.dot(random_arr1,random_arr2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [96]:
np.dot(random_arr1,random_arr2.T)

array([[42, 53, 58, 50],
       [48, 57, 57, 66],
       [57, 66, 78, 61],
       [45, 49, 65, 39]])

In [99]:
random_1 = np.random.randint(10, size = (3,3))
random_2 = np.random.randint(10, size = (3,3))

random_1.shape, random_2.shape,random_1,random_2


((3, 3),
 (3, 3),
 array([[8, 4, 4],
        [5, 3, 6],
        [6, 9, 8]]),
 array([[1, 9, 5],
        [0, 4, 5],
        [8, 5, 8]]))

In [100]:
random_1 > random_2

array([[ True, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [101]:
random_1 >= random_2

array([[ True, False, False],
       [ True, False,  True],
       [False,  True,  True]])

In [102]:
random_1 > 7


array([[ True, False, False],
       [False, False, False],
       [False,  True,  True]])

In [103]:
random_1 == random_2

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [108]:
random_2.shape

(3, 3)

In [110]:
%timeit np.sort(random_2.flatten())
%timeit sorted(random_2.flatten())

#hence numpy sort is faster then built in python sort method

5.51 μs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
6.02 μs ± 173 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [111]:
np.sort(random_1)

array([[4, 4, 8],
       [3, 5, 6],
       [6, 8, 9]])

In [115]:
random_1, np.sort(random_1, axis = 0)

(array([[8, 4, 4],
        [5, 3, 6],
        [6, 9, 8]]),
 array([[5, 3, 4],
        [6, 4, 6],
        [8, 9, 8]]))

In [119]:
np.argmax(random_1)

7

In [117]:
np.argmax(random_1,axis = 1)

array([0, 2, 1], dtype=int64)

In [122]:
np.argmin(random_1)

4

In [118]:
np.argmin(random_1,axis = 1)

array([1, 1, 0], dtype=int64)

In [123]:
np.random.normal(0,1,10)

array([-2.41993582,  0.68734357,  0.13490268, -0.11935184, -0.59381064,
        0.48126743,  0.46625893,  0.27486035, -1.18318911,  1.02102749])

In [125]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [142]:
np.random.seed(5)
items_data = np.random.randint(20,size = (5,3))
items_data

array([[ 3, 14, 15],
       [ 6, 16,  9],
       [ 8,  4,  7],
       [16, 16,  7],
       [12, 15, 17]])

In [143]:
items_data = pd.DataFrame(items_data,index = ["Mon","Tues","Wed","Thrus","Fri"],columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
items_data

Almond Butter  Peanut Butter  Cashew Butter
Mon                3             14             15
Tues               6             16              9
Wed                8              4              7
Thrus             16             16              7
Fri               12             15             17

In [150]:
prices = np.array([10,8,12])
prices.shape
transposed_price = prices.T
transposed_price.shape #so tranpose do not work 1d arrays

new_prices = prices.reshape(1,3)
new_prices.shape

(1, 3)

In [151]:
items_price = pd.DataFrame(new_prices,index = ["Price"],columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
items_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [158]:
total = np.dot(items_data,items_price.T)
total

array([[322],
       [296],
       [196],
       [372],
       [444]])

In [164]:
items_data["Total ($)"] = total
print(items_data)
print()
print(items_price)

       Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon                3             14             15        322
Tues               6             16              9        296
Wed                8              4              7        196
Thrus             16             16              7        372
Fri               12             15             17        444

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12


In [171]:
Data = items_data.copy()
price_row = items_price.copy()
price_row.index = ["Price"]
combination = pd.concat([Data,price_row])
combination.to_csv("Butter-sales.csv")